spring:
  application:
    name: java-course-spring
  datasource:
    url: jdbc:postgresql://junction.proxy.rlwy.net:45238/railway
    username: postgres
    password: WbsCPvalsQgWJoEzaRKSTbVHHUXRDjbg
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

springdoc:
  swagger-ui:
    urls:
      - url: /v3/api-docs
        name: countrly
    server:
      - url: https://exciting-wonder-production.up.railway.app

shape:
  resources:
    path: src/main/resources/shapes