-- INSERT INTO complexities (id, complexity, country_id)
-- VALUES (nextval('complexity_id_seq'), 'EASY', 1),
--        (nextval('complexity_id_seq'), 'MEDIUM', 2),
--        (nextval('complexity_id_seq'), 'HARD', 3),
--        (nextval('complexity_id_seq'), 'EASY', 4),
--        (nextval('complexity_id_seq'), 'MEDIUM', 5),
--        (nextval('complexity_id_seq'), 'HARD', 6),
--        (nextval('complexity_id_seq'), 'EASY', 7),
--        (nextval('complexity_id_seq'), 'MEDIUM', 8),
--        (nextval('complexity_id_seq'), 'HARD', 9),
--        (nextval('complexity_id_seq'), 'EASY', 10);
