-- INSERT INTO shapes (id, country_name, image, country_id)
-- VALUES (nextval('shape_id_seq'), 'United States', 'United States.png', 1),
--        (nextval('shape_id_seq'), 'Canada', 'Canada.png', 2),
--        (nextval('shape_id_seq'), 'United Kingdom', 'United Kingdom.png', 3),
--        (nextval('shape_id_seq'), 'Germany', 'Germany.png', 4),
--        (nextval('shape_id_seq'), 'France', 'France.png', 5),
--        (nextval('shape_id_seq'), 'Italy', 'Italy.png', 6),
--        (nextval('shape_id_seq'), 'Spain', 'Spain.png', 7),
--        (nextval('shape_id_seq'), 'Australia', 'Australia.png', 8),
--        (nextval('shape_id_seq'), 'Japan', 'Japan.png', 9),
--        (nextval('shape_id_seq'), 'Brazil', 'Brazil.png', 10);
